project:
    type: book

book:
    title: "Cognitive Models"
    subtitle: "Computational Modeling of Cognitive Processes with Bayesian Mixed Models in Julia"
    author: "Dominique Makowski"
    date: "03/07/2024"
    # image: "media/cover.jpg"
    cover-image: "media/cover.jpg"
    chapters:
        - index.qmd
        - 1_introduction.qmd
        - 2_predictors.qmd
        - 3_scales.qmd
        # - 4_rt.qmd
        - 5_individual.qmd
        - references.qmd

bibliography: references.bib

format:
    html:
        theme: cosmo
        code-fold: true

execute:
    cache: false
    # freeze: "auto"

jupyter: julia-1.10
