project:
    type: book

book:
    title: "Cognitive Models"
    subtitle: "Computational Modeling of Cognitive Processes with Bayesian Mixed Models in Julia"
    author:
        - name: "Dominique Makowski"
          url: https://realitybending.github.io/
          orcid: 0000-0001-5375-9967
          affiliation:
              - name: University of Sussex
                city: Brighton, UK
                url: https://www.sussex.ac.uk/
    date: "03/07/2024"
    cover-image: "media/cover.png"
    favicon: "media/cover.png"
    doi: https://doi.org/10.5281/zenodo.12685343
    chapters:
        - index.qmd
        - 1_introduction.qmd
        - 2_predictors.qmd
        - 3_scales.qmd
        - part: "Reaction Times"
          chapters:
              - 4a_rt_descriptive.qmd
              - 4b_rt_generative.qmd
        - 5_individual.qmd
        # - part: "Fundamentals"
        #   chapters:
        #       - 1_introduction.qmd
        # - part: "Predictors"
        #   chapters:
        #       - 2_predictors.qmd
        # - part: "Scales and Choices"
        #   chapters:
        #       - 3_scales.qmd
        # - part: "Individual Differences"
        #   chapters:
        #       - 5_individual.qmd
        - references.qmd
    sidebar:
        search: true
        title: "Cognitive Models"
        logo: "media/cover_image.png"
    navbar:
        title: "Cognitive Models: Computational Modeling of Cognitive Processes with Bayesian Mixed Models in Julia"
        right:
            - icon: github
              href: https://github.com/DominiqueMakowski/CognitiveModels
              aria-label: GitHub
    description: "This book provides a comprehensive introduction to cognitive modeling using Bayesian mixed models in Julia."
    downloads: pdf

bibliography: references.bib

format:
    html:
        theme: pulse
        code-fold: true
        number-depth: 3

execute:
    cache: true
    freeze: "auto"
    execute: true
    # cache: false
    # freeze: false
# engine: julia
# jupyter: julia-1.10
