on:
    workflow_dispatch:
    push:
        branches: main

name: Quarto Publish

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"
                  # cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade setuptools pip wheel
                  python -m pip install jupyter jupyter-cache

            - name: Install Julia
              uses: julia-actions/setup-julia@v2
              with:
                  version: "1.10"

            - name: Cache Julia packages
              uses: julia-actions/cache@v2

            - name: Install Julia dependencies
              run: |
                  julia -e 'import Pkg; Pkg.add("QuartoNotebookRunner"); Pkg.add("Plots")'

            - name: Render and Publish
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                  target: gh-pages
                  path: content/
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
